### ISSUE TITLE
Include node path on watch() 'changed' event

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hypertrie#24]
Any chance we could get the path of the changed file emitted in the `changed` event emitted by `watch()` ?

**Comment by mafintosh** [comment]
Ya it might be 100000s of files in case the update comes from a remote and you’ve been offline for a while

**Comment by mafintosh** [comment]
You can do a diff if you wanna that out tho

**Comment by pfrazee** [comment]
Good to know, thanks
