### ISSUE TITLE
What is the sort order of the trie?

### ISSUE THREAD

**Issue by xori** [mafintosh/hypertrie#28]
I've inserted a bunch of junk data into hypertrie, and given the following
```js
const it = db.iterator('path/a/b/', {
  random: false,
})
it.next(console.log)
it.next(console.log)
it.next(console.log)
it.next(console.log)
it.next(console.log)
```

I will get
```
null {
  seq: 116,
  key: 'path/a/b/0.9071345097354171',
  value: 0.8417110888179538
}
null {
  seq: 161,
  key: 'path/a/b/0.3813357394957859',
  value: 0.42573069510438866
}
null {
  seq: 186,
  key: 'path/a/b/0.42983427099270144',
  value: 0.04289104554710588
}
null {
  seq: 139,
  key: 'path/a/b/0.02566201512704991',
  value: 0.19759191402928877
}
null {
  seq: 110,
  key: 'path/a/b/0.8211549361126349',
  value: 0.4212390279547582
}
```

I would normally expect lexicographical ordering based on the key. But I'm not seeing that here. What order is it in?

**Comment by mafintosh** [comment]
It’s hash ordered

**Comment by xori** [comment]
To those (like me) that wanted a little more information. It seems the magic happens [here](https://github.com/mafintosh/hypertrie/blob/268a272e16d8e1367aca52c103a7caafd46fefc6/lib/node.js#L87-L103). 

Specifically `/` are special, and are very useful if you need to group things.

To my understanding, the keys are split on `/` and the contents are hashed to an 8 byte subhash and then concat'ed together. No idea what happens on collision. ( Maybe you can point me to some code @mafintosh )

Changing the path on my example showed it pretty plainly.
```
null {
  seq: 64,
  key: 'path/a/z/0.2/5459611804240003',
  value: 0.9698631498407253
}
null {
  seq: 97,
  key: 'path/a/z/0.2/9428217908481793',
  value: 0.3504731934349341
}
null {
  seq: 41,
  key: 'path/a/z/0.2/498376865046943',
  value: 0.1141990320554318
}
null {
  seq: 19,
  key: 'path/a/z/0.8/496758283522867',
  value: 0.7448252071136965
}
null {
  seq: 95,
  key: 'path/a/z/0.8/464439961812704',
  value: 0.8146415891623289
}
```

**Comment by mafintosh** [comment]
Yes exactly. When a collision occurs it’s sorted by the key.
