### ISSUE TITLE
.put method CAS semantics over network

### ISSUE THREAD

**Issue by kishoreannapureddy** [mafintosh/hypertrie#34]
'db.put' method provides atomic compare-and-swap capability. Is this operation atomic when put operations happen over network on two different nodes or only in the same process?

**Comment by mafintosh** [comment]
Yep, put is always atomic

**Comment by kishoreannapureddy** [comment]
@mafintosh is this because there is only one writer? does this hold even if there are multiple writers across nodes?

I am seeing local locking code here: https://github.com/mafintosh/hypertrie/blob/master/lib/put.js#L40-L46

**Comment by mafintosh** [comment]
Yep cause a single writer and the writes are done in an atomic batch on the hypercore

**Comment by kishoreannapureddy** [comment]
Sorry for mutliple questions, but is hypercore feed.replicate two way sync?

**Comment by mafintosh** [comment]
Depends on what you mean by two way. The remote can fetch data from the local peer and vice versa yes.
